all:
    children:
        master:
            hosts:
                kvm_server:
                    ansible_host: 172.28.30.92
        mc_oel:
            hosts:
                vn7ms_mc0_oel:
                    ansible_host: '3333:6666:8888:600:11:10:228:F1'
                    node_id: 0
                vn7ms_mc1_oel:
                    ansible_host: '3333:6666:8888:600:11:10:228:F2'
                    node_id: 1
                vn7ms_mc2_oel:
                    ansible_host: '3333:6666:8888:600:11:10:228:F3'
                    node_id: 2
        db_oel:
            hosts:
                vn7ms_db0_oel:
                    ansible_host: '3333:6666:8888:600:11:10:228:F4'
                    node_id: 0
                vn7ms_db1_oel:
                    ansible_host: '3333:6666:8888:600:11:10:228:F5'
                    node_id: 1
        app_oel:
            hosts:
                vn7ms_app0_oel:
                    ansible_host: '3333:6666:8888:600:11:10:228:F6'
                    ansible_host_eth1_v4: '192.168.9.110'
                    ansible_host_eth1_v6: '3333:6666:8888:600:11:10:229:110'
                    node_id: 0
                vn7ms_app1_oel:
                    ansible_host: '3333:6666:8888:600:11:10:228:F7'
                    ansible_host_eth1_v4: '192.168.9.111'
                    ansible_host_eth1_v6: '3333:6666:8888:600:11:10:229:111'
                    node_id: 1
        cs_oel:
            hosts:
                vn7ms_cs0_oel:
                    ansible_host: '3333:6666:8888:600:11:10:228:F8'
                    ansible_host_eth1_v4: '192.168.9.112'
                    ansible_host_eth1_v6: '3333:6666:8888:600:11:10:229:112'
                    node_id: 0
                vn7ms_cs1_oel:
                    ansible_host: '3333:6666:8888:600:11:10:228:F9'
                    ansible_host_eth1_v4: '192.168.9.113'
                    ansible_host_eth1_v6: '3333:6666:8888:600:11:10:229:113'
                    node_id: 1
        mc_redhat:
            hosts:
                litecore_mc0_redhat:
                    ansible_host: '2023:2:2:1::30a'
                    ansible_host_eth1_v4: '192.168.9.113'
                    ansible_host_eth1_v6: '3333:6666:8888:600:11:10:229:113'
                    hostname: 'dev-lcnms_mc_redhat_in_0'
                    vcpu: 4
                    vmemory: 8388608   #kib
                    vdb: 20
                    vdc: 20
                    vdd: 60
                    node_id: 0
                litecore_mc1_redhat:
                    ansible_host: '2023:2:2:1::30b'
                    ansible_host_eth1_v4: '192.168.9.113'
                    ansible_host_eth1_v6: '3333:6666:8888:600:11:10:229:113'
                    hostname: 'dev-lcnms_mc_redhat_in_1'
                    vcpu: 4
                    vmemory: 8388608   #kib
                    vdb: 20
                    vdc: 20
                    vdd: 60
                    node_id: 1
                #litecore_mc2_redhat:
                #    ansible_host: '2023:2:2:1::30c'
                #    ansible_host_eth1_v4: '192.168.9.113'
                #    ansible_host_eth1_v6: '3333:6666:8888:600:11:10:229:113'
                #    hostname: 'dev-lcnms_mc_redhat_in_2'
                #    node_id: 2
        db_redhat:
            hosts:
                litecore_db0_redhat:
                    ansible_host: '2023:2:2:1::30d'
                    ansible_host_eth1_v4: '192.168.9.113'
                    ansible_host_eth1_v6: '3333:6666:8888:600:11:10:229:113'
                    hostname: 'dev-lcnms_db_redhat_in_0'
                    vcpu: 8
                    vmemory: 33554432   #kib
                    vdb: 80
                    vdc: 300
                    vdd: 800
                    node_id: 0
                #litecore_db1_redhat:
                #    ansible_host: '2023:2:2:1::30e'
                #    ansible_host_eth1_v4: '192.168.9.113'
                #    ansible_host_eth1_v6: '3333:6666:8888:600:11:10:229:113'
                #    hostname: 'dev-lcnms_db_redhat_in_1'
                #    node_id: 1
        app_redhat:
            hosts:
                itecore_app0_redhat:
                    ansible_host: '2023:2:2:1::304'
                    ansible_host_eth1_v4: '172.28.30.228'
                    ansible_host_eth1_v6: '2023:2:2:0::104'
                    hostname: 'dev-lcnms_app_redhat_in_0'
                    vcpu: 8
                    vmemory: 33554432   #kib
                    vdb: 80
                    vdc: 20
                    node_id: 0
                #litecore_app1_redhat:
                #    ansible_host: '2023:2:2:1::305'
                #    ansible_host_eth1_v4: '172.28.30.229'
                #    ansible_host_eth1_v6: '2023:2:2:0::105'
                #    hostname: 'dev-lcnms_app_redhat_in_1'
                #    node_id: 1
        cs_redhat:
            hosts:
                litecore_cs0_redhat:
                    ansible_host: '2023:2:2:1::307'
                    ansible_host_eth1_v4: '172.28.30.231'
                    ansible_host_eth1_v6: '2023:2:2:0::107'
                    hostname: 'dev-lcnms_cs_redhat_in_0'
                    vcpu: 8
                    vmemory: 33554432   #kib
                    vdb: 80
                    vdc: 20
                    node_id: 0
                #litecore_cs1_redhat:
                #    ansible_host: '2023:2:2:1::308'
                #    ansible_host_eth1_v4: '172.28.30.232'
                #    ansible_host_eth1_v6: '2023:2:2:0::108'
                #    hostname: 'dev-lcnms_cs_redhat_in_1'
                #    node_id: 1
        mc_centos:
            hosts:
                vn7ms_mc0_centos:
                    ansible_host: '3333:6666:8888:600:11:10:228:1'
                    node_id: 0
                vn7ms_mc1_centos:
                    ansible_host: '3333:6666:8888:600:11:10:228:2'
                    node_id: 1
                vn7ms_mc2_centos:
                    ansible_host: '3333:6666:8888:600:11:10:228:3'
                    node_id: 2
        db_centos:
            hosts:
                vn7ms_db0_centos:
                    ansible_host: '3333:6666:8888:600:11:10:228:4'
                    node_id: 0
                vn7ms_db1_centos:
                    ansible_host: '3333:6666:8888:600:11:10:228:5'
                    node_id: 1
        app_centos:
            hosts:
                vn7ms_app0_centos:
                    ansible_host: '3333:6666:8888:600:11:10:228:6'
                    ansible_host_eth1_v4: '192.168.9.100'
                    ansible_host_eth1_v6: '3333:6666:8888:600:11:10:229:100'
                    node_id: 0
                vn7ms_app1_centos:
                    ansible_host: '3333:6666:8888:600:11:10:228:7'
                    ansible_host_eth1_v4: '192.168.9.101'
                    ansible_host_eth1_v6: '3333:6666:8888:600:11:10:229:101'
                    node_id: 1
        cs_centos:
            hosts:
                vn7ms_cs0_centos:
                    ansible_host: '3333:6666:8888:600:11:10:228:8'
                    ansible_host_eth1_v4: '192.168.9.102'
                    ansible_host_eth1_v6: '3333:6666:8888:600:11:10:229:102'
                    node_id: 0
                vn7ms_cs1_centos:
                    ansible_host: '3333:6666:8888:600:11:10:228:9'
                    ansible_host_eth1_v4: '192.168.9.103'
                    ansible_host_eth1_v6: '3333:6666:8888:600:11:10:229:103'
                    node_id: 1
        openEulerImage:
            hosts:
                oel_2103_eth_test:
                    node_id: 0
                    ansible_host: '192.168.9.92'
                    ansible_host_eth1_v4: '192.168.9.112'
                    ansible_host_eth1_v6: '3333:6666:8888:600:11:10:229:112'
    vars:
        ansible_port: 22
        ansible_user: root
        ansible_password: "-abc0mN&MS"
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        kvm_clone_from:
            acm_vm_name: "litecore_acm_image_redhat8.6_v01"
            db_vm_name: "litecore_db_image_redhat8.6_v01"
            default_vm_ip: "172.28.30.236"
            # acm_vm_name: "vn7ms_acm_image_openeuler21.03_v06"
            # db_vm_name: "vn7ms_db_image_openeuler21.03_v06"
            # default_vm_ip: "192.168.9.98"
            # acm_vm_name: "vn7ms_acm_image_c2009_v19"
            # db_vm_name: "vn7ms_db_image_c2009_v19"
            # default_vm_ip: "192.168.9.91"
        default_sleep_timeout: 10 #seconds
        eth0_alias: 'eth0'
        eth1_alias: 'eth1'
        eth1_mask: '255.255.255.240'
        eth1_gtwy: '172.28.30.225'
        local_dns_ip: '172.28.30.225'
        vn7ms_env:
            DB_DATABASE: vn7ms
            DB_USERNAME: n7ms
            DB_PASSWORD: '-abc0mN&MS'